---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xyt99.
--- DateTime: 2023/10/7 18:57
---
---- 参数
--local voucherId = ARGV[1]
--local userId = ARGV[2]
---- 数据key
--local stockKey = 'seckill:stock:' .. voucherId
--local orderKey = 'seckill:order:' .. voucherId
---- 库存判断
--if (tonumber(redis.call('get', stockKey)) <= 0) then
--    -- 库存不足
--    return 1
--end
---- 一人一单判断
--if (redis.call('sismember', orderKey, userId) == 1) then
--    -- 重复下单
--    return 2
--end
---- 扣减库存
--redis.call('incrby', stockKey, -1)
---- 保存到set orderKey对应秒杀券的下单用户set，stockKey对应秒杀券的库存
--redis.call('sadd', orderKey, userId)
--return 0;
-- modified time: 2023/11/9
-- 判断秒杀资格并放入消息队列
-- 参数
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
--库存key
local stockKey = 'seckill:stock:' .. voucherId
--订单key
local orderKey = 'seckill:order:' .. voucherId
--库存是否充足
--库存不足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end

--判断用户是否下单
--存在用户 禁止重复下单
if (tonumber(redis.call('sismember', orderKey, userId)) == 1) then
    return 2
end
-- 扣减库存
redis.call('incrby', stockKey, -1)
-- 保存到set orderKey对应秒杀券的下单用户set，stockKey对应秒杀券的库存
redis.call('sadd', orderKey, userId)
-- 发送到消息队列
--redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0