---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xyt99.
--- DateTime: 2023/10/7 18:57
---
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0